### ISSUE TITLE
테스트 데이터 추가

### ISSUE THREAD

**Issue by belljun3395** [YAPP-Github/24th-Web-Team-1-BE#232]
https://linear.app/fewletter/issue/DEV-39/테스트-데이터-추가

**Comment by hun-ca** [comment]
DataGrip에서 테이블에 들어있는 데이터 Insert 쿼리로 뽑아내는거 참고

**Comment by hun-ca** [comment]
실행게획 뽑을때 넣을 데이터 이슈인가요?

**Comment by hun-ca** [comment]
이슈 민들라했는데 이미 이걸로 있는거 같아서

**Comment by belljun3395** [comment]
아 아뇨! 요건 로컬 환경에서 실행할때 필요한 기본 데이터 추가하려고요
