### ISSUE TITLE
[lint] ktlint 룰 표준으로 스타일 재지정

### ISSUE THREAD

**Issue by hun-ca** [YAPP-Github/24th-Web-Team-1-BE#458]
- 코틀린 스타일 코틀린 표준 문서 참고 : https://kotlinlang.org/docs/code-style-migration-guide.html#in-maven

**Comment by belljun3395** [comment]
핀터레스트 ktlint: https://pinterest.github.io/ktlint/latest/install/integrations/#custom-gradle-integration-with-kotlin-dsl
