### ISSUE TITLE
CI 액션 구현

### ISSUE THREAD

**Issue by belljun3395** [YAPP-Github/24th-Web-Team-1-BE#95]

**Comment by hun-ca** [comment]
@belljun3395 build.gralde에 도커 빌드 만드는 잡은 다른 파일에 넣고 build.gralde에서 참조하게 하도록 가능?

**Comment by belljun3395** [comment]
.kt 가 아니면 가능한데
.kt 에서는 아직 모르겠어요

**Comment by hun-ca** [comment]
ㅇㅋ 그럼 일단 하고 나중에 수정 ㄱ
